### ISSUE TITLE
[BUG]: Cannot fetch external links from $ref due inputStream.once error

### ISSUE THREAD

**Issue by sergialonsaco** [glideapps/quicktype#2613]
When generating an output in Go, Java or Python for a JsonSchema that contains an external link reference using the $ref key, Quicktype should resolve it by fetching that URL to download the schema. Still, it's showing the following error instead:

```bash
Error: Cannot read from file or URL https://raw.githubusercontent.com/cloudevents/spec/v1.0.2/cloudevents/formats/cloudevents.json: TypeError: inputStream.once is not a function
```

**Important note**: this issue is not reproducible in lower versions like `23.0.106`.

## Issue Type

Issue with input parsing of JSON schemas with external link references (using $ref)

## Context (Environment, Version, Language)

Input Format: JSONSchema
Output Language: Go, Java, Python

CLI, npm, or app.quicktype.io: npm package
Version: 23.0.170

## Description

Autogenerate code to use JSON schemas in different languages like Go, Java or Python.
In lower versions of the Quicktype package, like `23.0.106,` this issue does not occur, and everything works as expected, but updating to the latest (`23.0.170`) reproduced the issue.

## Input Data

```json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "description": "test schema",
    "type": "object",
    "allOf": [
      {
        "$ref": "https://raw.githubusercontent.com/cloudevents/spec/v1.0.2/cloudevents/formats/cloudevents.json"
      }
    ]
  }
 
```
## Expected Behaviour / Output

As it happens with lower versions, it should generate the code in the expected language correctly.

## Current Behaviour / Output

Outputs an error and doesn't generate the code.

## Steps to Reproduce

1. Using quicktype as npm package dependency version 23.0.170
2. Running an npm script with "quicktype -s schema test_schema.json -o schema.go" where `test_schema.json` has an external link (similar to the input data provided).

**Comment by jgadling** [comment]
Chiming in here, I'm running into the same issue using Node 18 on the command line.

I played with `git bisect` a bit and it looks like this was originally broken by #2573. That change seems to have caused a bunch of other breakages for CI and required other tweaks afterwards, because in some environments `fetch` is returning a [ReadableStream](https://nodejs.org/dist/v18.20.6/docs/api/webstreams.html#class-readablestream) rather than a [Readable](https://nodejs.org/dist/v18.20.6/docs/api/stream.html#class-streamreadable)

Can we consider whether the

**Comment by Gpinchon** [comment]
Was this ever fixed ? Now Quicktype replaces `$ref` with a class containing a `string` named `ref` which is not very helpful...

**Comment by schani** [comment]
**Triage note** (systematic backlog sweep, assisted by Claude): confirmed reproducible on current master (v23.3.0, `68ecb284`).

**Root cause**: this is the regression from #2573 that a couple of commenters already flagged. `readableFromFileOrURL` in `packages/quicktype-core/src/input/io/NodeIO.ts` (~line 64) prefers `global.fetch` (undici) and casts `response.body` — a WHATWG `ReadableStream` — directly to a Node `readable-stream` `Readable`:

```ts
return defined(response.body) as unknown as Readable;
```

Downstream, `get-stream` calls `.once`/`.pipe` on that value, which don't exist on a WHATWG stream, producing the reported `TypeError: inputStream.once is not a function`.

Compounding this, `JSONSchemaStore.get` in `packages/quicktype-core/src/input/JSONSchemaStore.ts` (~line 33-35) swallows the fetch error in an empty catch block:

```ts
} catch (e) {
    // FIXME: handle or log this error
}
```

so from the CLI the only symptom is a generic "Could not fetch schema ..." rather than the real exception — you have to call `readFromFileOrURL` directly to see the actual `TypeError`.

**Assessment**
- Severity: high — any JSON Schema with an external (or even same-origin non-CLI) URL `$ref` fails to resolve, silently in the CLI's normal error path.
- Difficulty: easy — swap in `stream.Readable.fromWeb(response.body)` (or use `await response.text()` and construct a Readable/string source directly) in `readableFromFileOrURL`; also stop swallowing the fetch error in `JSONSchemaStore.get` so failures are visible.

**Reproduction**:
```
timeout 120 node dist/index.js -s schema --lang go test_schema.json
```
```json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "description": "test schema",
    "type": "object",
    "allOf": [
      {
        "$ref": "https://raw.githubusercontent.com/cloudevents/spec/v1.0.2/cloudevents/formats/cloudevents.json"
      }
    ]
}
```
Calling `readFromFileOrURL` directly on that URL surfaces the real error:
```
FAILED: Cannot read from file or URL https://raw.githubusercontent.com/cloudevents/spec/v1.0.2/cloudevents/formats/cloudevents.json: TypeError: inputStream.once is not a function
```
